[package]
name = "cpp-relative-includes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.0", features = ["derive"] }
regex = "1.10.4"
walkdir = "2.5.0"
